"$schema" = 'config-schema.json'

format = """
($username$hostname[| ](bg:base fg:text))\
$directory\
([|](bg:base fg:text)$git_branch$git_status)\
$fill \
([](fg:surface0)$conda[](fg:surface0))\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[username]
format = '[ $user ]($style)'
style_root = "bg:base fg:bold rosewater"
style_user = "bg:base fg:bold rosewater"

[hostname]
format = "[󰁥 $hostname ]($style)"
ssh_only = true
style = "bg:base fg:bold rosewater"
trim_at = '.companyname.com'

[directory]
format = "[  $path ]($style)"
style = "bg:base fg:peach"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"/adenauer" = "/ "
"/arbitrator" = "/󰦻 "
"/.config" = "/ "

[git_branch]
format = '[[ $symbol $branch ](bg:base fg:blue)]($style)'
style = "bg:base"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind )](bg:base fg:blue)]($style)'
style = "bg:base"

[fill]
symbol = " "

[conda]
format = "[$symbol$environment]($style)"
style = "bg:surface0 fg:text"
symbol = " "

[character]
error_symbol = '[](bold fg:red)'
success_symbol = '[](bold fg:green)'

